<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clientes extends Model
{
    protected $table='clientes';
    protected $fillable = [
    'name',
    'segundoNombre',
    'apePat',
    'fechaNacimiento',
    'lugarNacimiento',
    'edad',
    'celular',
    'telCasa',
    'telOficina',
    'religion',
    'escolaridad',
    'email',
    'sexo',
    'edoCivil',
    'pais',
    'estado',
    'calle',
    'ciudad',
    'codigoPostal',
    'enteroNosotros',
    'especifiqueEnteroNosotros',
    'aseguradora',
    'tipoSangre',
    'cirugiasPrevias',
    'otrasCirugias',
    'emerNombre',
    'emerRelacion',
    'emerTel',
    'imagen',
    'ocupacionSeccion2',
    'diagnosticoPreOperatorio',
    'procedimientoQuirurgico',
    'planQuirurgico',
    'cuidadoTerapeutico',

    //Seccion 2

    'originariaSeccion2',
    'resideSeccion2',
    'ahfSeccion2',
    'apnpSeccion2',
    'appSeccion2',
    'agoSeccion2',
    'padecimientoSeccion2',
    'exploracionFisicaSeccion2',
    'laboratorioSeccion2',
    'idxSeccion2',
    'planSeccion2',

    //Seccion 3
    'peso_seccion3',
    'talla_seccion3',
    'ta_seccion3',
    'fc_seccion3',
    'fr_seccion3',
    'temp_seccion3',
    'actividad_fisica_seccion3',
    'subir_escaleras_seccion3',
    'cuantos_pisos_seccion3',
    'sangrar_excesivamente_seccion3',
    'reacciones_anormales_seccion3',
    'reacciones_anormales_anestesia_seccion3',
    'fiebre_anestesia_seccion3',
    'alergico_medicamentos_seccion3',
    'cuales_medicamentos_seccion3',
    'reacciones_seccion3',
    'alergico_cinta_adhesiva_seccion3',
    'alergico_oido_seccion3',
    'bebidas_alcoholicas_seccion3',
    'abstenido_bebidas_alcoholicas_seccion3',
    'sufre_delirios_seccion3',
    'fuma_seccion3',
    'transfusion_sanguinea_seccion3',
    'reaccion_transfusion_sanguinea_seccion3',
    'reaccion_transfusion_seccion3',
    'embarazada_seccion3',
    'menstruacion_seccion3',
    'corazon_seccion3',
    'angina_seccion3',
    'adiccion_drogas_seccion3',
    'dolores_cabeza_seccion3',
    'enfermedades_mentales_seccion3',
    'embolia_pulmonar_seccion3',
    'enfermedades_articulares_seccion3',
    'fracturas_seccion3',
    'problemas_columna_seccion3',
    'desmayos_seccion3',
    'enfermedades_pulmones_seccion3',
    'asma_seccion3',
    'tiroides_seccion3',
    'tuberculosis_seccion3',
    'enfermedades_musculares_seccion3',
    'bronquitis_seccion3',
    'enfisema_seccion3',
    'embolia_cerebral_seccion3',
    'varices_seccion3',
    'estrabismo_seccion3',
    'glaucoma_seccion3',
    'hepatitis_seccion3',
    'presion_alta_seccion3',
    'diabetes_seccion3',
    'flebitis_seccion3',
    'abstinencia_drogas_seccion3',
    'enfermedad_rinones_seccion3',
    'moretones_seccion3',
    'fc_seccion3',
    'fecha_ultimo_examen_seccion3',
    'fecha_ultima_radiografia_seccion3',
    'fecha_ultimo_electrocardiograma_seccion3',
    'clase_anestesia_seccion3',
    'fiebre_operaciones_previas_seccion3',
    'dientes_postizos_seccion3',
    'faltan_dientes_seccion3',
    'dientes_porcelana_seccion3',
    'dientes_sueltos_seccion3',
    'dificulta_mover_boca_seccion3',
    'lentes_contacto_seccion3',
    'pestanas_seccion3',
    'ojo_artificial_seccion3',
    'defectos_mayores_seccion3',
    'aspirina_seccion3',
    'oxigeno_seccion3',
    'digitales_seccion3',
    'lsd_seccion3',
    'quinidinas_seccion3',
    'glaucoma_seccion3',
    'nitroglicerina_seccion3',
    'pastillas_dormir_seccion3',
    'medicamentos_presion_seccion3',
    'narcoticos_seccion3',
    'diureticos_seccion3',
    'lasix_seccion3',
    'anticoagulantes_seccion3',
    'heparina_seccion3',
    'medicamentos_diabetes_seccion3',
    'otro_medicamento_seccion3',
    'tranquilizantes_seccion3',
    'cual_otro_medicamento_seccion3',
    'antidepresivos_seccion3',
    'dosis_seccion3',
    'gotas_glaucoma_seccion3',
    'padece_alergia_material_seccion3'
    

    ];
}
